
[font]
normal = { family = "MapleMono Nerd Font Mono", style = "Regular" }
size = 18.0

[window]
padding = { x = 8, y = 8 }
option_as_alt = "OnlyLeft"

[general]
import = [
	"~/.config/alacritty/themes/everforest_dark.toml"
]

[terminal]

[terminal.shell]
program = "zsh"
